### PR TITLE
Adjusted Concentration Spells for Wildshape and Call Lightning

### PR DESCRIPTION
**Pull request by Celestro**

### CODE REVIEW

**Comment by FelipeRenault** [comment]
♻️ @Celestro I've made the following changes:
- Decided to make the first cast of Call Lightning only create the area, so the range indicator shows the full area that will rain.
- On the turn the spell is cast, you can use the free action to call lightning on a radius. On subsequent turns, it will cost an action. I have to adjust the localization entries to better explain this
- Changed the target conditions for the damaging spells, in a way that it highlights the characters which will be affected, providing better clarity to the player if someone is on the edge of the rain
- Removed the `DestructiveWrath()` conditions, since it wasn't working (perhaps it's something on your mod you forgot to port over?)
- Provided a localization for the aura status, since yours was using a non-existing one

**Comment by Celestro** [comment]
Yeah I was actually going to suggest a change on Call Lightning to establish the area first and all that since someone did mention it was kind of awkward.

**Comment by FelipeRenault** [comment]
Then it's necessary to include the Destructive Wrath function on this mod as well, even if it relies on non-existing statuses or passives, because calling the non-existing function was causing the spell to deal no damage at all. And should this be a fix present on RAW, 5e or both?

**Comment by Celestro** [comment]
Actually, testing it earlier, it turns out it does work. It didn't appear that would be the case but apparently it functions differently than the other MinimumRollResult Boosts so it's fine for that one to be gone altogether.

**Pull request closed without merging**
