### PR TITLE
See Invisibility Rework

### PR DESCRIPTION
**Pull request by drkekyll**
Added copies of all invisibility statuses with modified boost lines.
Removed `SEE_INVISIBILITY_SEEN` from `SEE_INVISIBILITY` aura. Now just applies `SEE_INVISIBILITY_REVEAL`.
Invisibility statuses are replaced with modified copies when removed by `SEE_INVISIBILITY_REVEAL`.
When `SEE_INVISIBILITY_REVEAL` is removed, original invisibility statuses are replaced.
NPC short range invisibility detection duration changed because at 0 duration it simply removed invisibility.
Checks for `_SEEN` invisibility statuses and ability to sense invisible creatures added to reaction interrupts based on moving in and out of weapon range.
Also modified removal conditions on invisibility. It's no longer removed by taking damage, but is removed by any attack whether it successfully deals damage or not.

### CODE REVIEW

**Comment by drkekyll** [comment]
Also modified removal conditions on invisibility. It's no longer removed by taking damage, but is removed by any attack whether it successfully deals damage or not.

**Comment by drkekyll** [comment]
I have also been working on an edit that adds Stealth checks and the ability to make an active Perception check to try and find sneaking invisible creatures, but Eric was saying that NPCs don't really use stealth and don't have the means to use it intelligently, so the only thing it adds is the ability to avoid the NPC seek ability by sneaking while invisible.

**Comment by FelipeRenault** [comment]
Well, invisibility gives you heavily obscured against creatures that can't see invisible. That's all there is to it. It gives you the prerequisite to TRY to sneak, but if the enemy can see invisible, there's not even a stealth check to find the sneaking invisible creature. Seeing invisible completely nullifies invisibility and we're back to normal stealth rules, so if you're out in the open, there shouldn't even need a sneak check against perception, you're instantly seen.
I didn't get to test the changes you've made, but my only suggestion would be to make sure the aura that reveals invisible creatures have a LOS check, so we simulate the "out in the open" part at least

**Comment by drkekyll** [comment]
Well, technically, See Invisible only counters the first bullet of the invisible condition that talks about seeing the creature, so I didn't put the `RAW_CanSeeInvisibleTarget()` check on the advantage boosts. I interpreted it the same way I interpret Shadow of Moil's "you ... become heavily obscured to others" clause. It's its own benefit unrelated to the light level rules. If you interpret the invisible condition differently, I can easily add the check to the advantage boosts.

I recognize this is a pedantic interpretation. I have no real preference, I just default to pedantry in cases of RAW.

**Comment by FelipeRenault** [comment]
This is one of the rare instances where I disagree with Sage Advice, JC, or whatever. It feels super weird to me that an invisible creature still gets adv on atk rolls (and causes disadv on attacks against it) when matched against a creature that can see invisible
See Invisibility is already super niche, since it's only useful against invisible creatures, so it's a reaction to something the opponent does, contrary to choosing to go invisible, which works most of the time. This makes preparing See Invisibility a large sacrifice of your prepared slots, and to make it so the few times when it's useful, be weak, is very weird. I'd argue that characters with true sight or that cast See Invisibility treat invisible enemies as if they weren't invisible at all - pretty much as if they didn't have the status against them.

**Comment by drkekyll** [comment]
I disagree with Sage Advice a lot, so you'll get no complaints from me. I'll add the checks to the boosts.

**Comment by drkekyll** [comment]
After a little more testing, I noticed that making an opportunity attack no longer seem to break invisibility. Also, the `RAW_CanSeeInvisible()` check seems to work for everything but the blind fighting check, but I guess that's a me problem since it's not in the vanilla game and I added it out of habit.

**Comment by FelipeRenault** [comment]
Sorry for taking this long to look into it. Now that I've released v4.0.0.0 and the mod is fully optionable, I'll return to testing this

**Comment by drkekyll** [comment]
No problem. Just fixed an issue with Greater Invis not going away if you were detected and concentration broke.
Also made the reveal status remove itself if you lose invis so you'd reappear properly, but in retrospect that might be better fixed with changing which status has the effect attached to it.
Removed a bunch of extra closing parentheses too.

`data "InterruptFlags" "InterruptWhileInvisible"` can be added to AoO and the PAM and WarCaster interrupts to make them work while invisible, but I didn't do that because, not having played the game, I don't know how important it is that enemies don't AoO when they're invisible.

**Comment by drkekyll** [comment]
I went ahead and added the facing check so you can test it out whenever you get back to the mod.

**Comment by drkekyll** [comment]
Alternatively there's `IsInSightPyramid(context.Source,context.TargetPosition)` if you want the narrower sight cone.

**Comment by drkekyll** [comment]
Narrowing the effect to the sight cone in testing made it painfully obvious how short the range on Detect Invisibility is. RAW it has no range, so I increased it to the range given for hero characters in Character.txt.

**Comment by drkekyll** [comment]
Also removed those entity interaction remove events from most of the invisibility statuses.

**Pull request merged**
